language: generic

matrix:
  include:
    - os: linux
      sudo: required
      services: docker
      env: myconfig=maxset with_coverage=true
    - os: linux
      sudo: required
      services: docker
      env: myconfig=maxset image=ubuntu-python3

script:
  - maintainer/CI/build_docker.sh
