language: generic

matrix:
  include:
    - os: linux
      sudo: required
      services: docker
      env: myconfig=nocheck-maxset make_check=false

script:
        - maintainer/travis/build_docker.sh
